[package]
disabled = true

[golang]
disabled = true

[lua]
disabled = true

[nix_shell]
disabled = true
impure_msg = ""
pure_msg = "[pure shell](bold green)"
format = '[$state(\($name\))](bold blue) '

[nodejs]
disabled = true

[terraform]
disabled = true

[git_branch]
symbol = ""

[docker_context]
disabled = true

[kubernetes]
disabled = true

[java]
disabled = true
